# Fase de compilación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /out

# Fase de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

# Forzar que escuche en el puerto 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "CongresoUMG.dll"]



